#Project Euler problem 29
#How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?


terms<-{}
for(a in 2:100){
  for(b in 2:100){
    terms<-union(terms,a^b)
  }
}
length(terms)
