#Project Euler problem 44

#Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. 
#The first ten pentagonal numbers are:  
#  1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#It can be seen that P4 + P7 = 22 + 70 = 92 = P8. 
#However, their difference, 70 − 22 = 48, is not pentagonal.
#Find the pair of pentagonal numbers, Pj and Pk, for which their sum and 
#difference are pentagonal and D = |Pk − Pj| is minimised. 
#What is the value of D?


is.wholenumber <-  function(x, tol = .Machine$double.eps^0.5){
  abs(x - round(x)) < tol
}

pentagonal <- function(n){
  return(n*(3*n-1)/2)
}

is.pentagonal <- function(n){
  return(is.wholenumber(1/6*(1+sqrt(24*n+1))))
}

# Start the clock!
ptm <- proc.time()

k <- 0
j <- 0
done <- FALSE
while(!done && k < 10000){
  k <- k+1
  j <- 0
  while(!done && j < k){
    j <- j+1
    if(is.pentagonal(pentagonal(k)+pentagonal(j)) && 
       is.pentagonal(pentagonal(k)-pentagonal(j))){
      done <- TRUE
    }
  }
}


# Stop the clock
time <- proc.time() - ptm

cat("Answer:", pentagonal(k)-pentagonal(j), "\n")
cat("time:",time)
